### ISSUE TITLE
Kuatham installation Issue

### ISSUE THREAD

**Issue by usman151mrd** [iocroblab/kautham#2]
I have make successfully khuatham from source code but when i run sudo make install it create following error please sir provide me a solution of that error i am very thankful to you
```shell
usman@usman:~/installation/kautham/build$ sudo make install
[sudo] password for usman: 
Traceback (most recent call last):
  File "/opt/ros/melodic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py", line 41, in <module>
    from genmsg import EXT_MSG, EXT_SRV, MsgContext
ImportError: No module named genmsg
CMakeFiles/_kautham_generate_messages_check_deps_SetPlannerParameter.dir/build.make:57: recipe for target 'CMakeFiles/_kautham_generate_messages_check_deps_SetPlannerParameter' failed
make[2]: *** [CMakeFiles/_kautham_generate_messages_check_deps_SetPlannerParameter] Error 1
CMakeFiles/Makefile2:2664: recipe for target 'CMakeFiles/_kautham_generate_messages_check_deps_SetPlannerParameter.dir/all' failed
make[1]: *** [CMakeFiles/_kautham_generate_messages_check_deps_SetPlannerParameter.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by lepalom** [comment]
please could you write some about your setup? OS, version, etc

**Comment by usman151mrd** [comment]
Ubuntu  18.04 Ros melodic

**Comment by usman151mrd** [comment]
I have solve this issue thanks please help me next generated issue. i am very thankful to you

**Comment by lepalom** [comment]
if you want, try this packages:
https://launchpad.net/~deb-rob/+archive/ubuntu/ros-bionic

here is kautham. What you need is to add the repo and after:

apt-get install kautham-tools kautham-ros-osrf

**Comment by Occy88** [comment]
hey I have the same issue, would love to know how you solved it. genmsg is found without sudo but with sudo it isn't there.

**Comment by lepalom** [comment]
Again, could you explain your setup?

**Comment by FahadRazaKhan** [comment]
@usman151mrd how did you solve this error?

**Comment by usman151mrd** [comment]
> @usman151mrd how did you solve this error?

can you explain the OS and its version?
I have used Ubuntu 20.04 and run these commands before compiling the source code

```
sudo apt-get install libompl-dev cmake libboost-system-dev libboost-serialization-dev libboost-thread-dev libfcl-dev libassimp-dev  libarmadillo-dev libode-dev libpugixml-dev libeigen3-dev   freeglut3-dev libsoqt520-dev libcoin-dev libroscpp-dev libtrajectory-msgs-dev  ros-message-generation

sudo apt-get install kautham-tools kautham-ros-osrf
```
from first-line few packages not found. you should remove those package and run apt with the remaining packages.
then run the second line of apt and now you can successfully compile the Kautham from the source thanks.  It will work on both 
Ubuntu 18.04 and 20.04 on my systems.
