### ISSUE TITLE
Kautham Running Problem

### ISSUE THREAD

**Issue by usman151mrd** [iocroblab/kautham#3]
After make and successfully installation still i am not able to run kautham. if i run from build folder it generate segmentation error and if i run from command kautham-gui libkautham.so.4.0 cannot find. please sir help me to solve this problem. in early versions kautham-gui file replace in app/graphical and now it have replace in devel/lib/kautham 

```shell
usman@usman:~/installation/kautham/build/devel/lib/kautham$ ./kautham-gui
Segmentation fault (core dumped)
usman@usman:~/installation/kautham/build/devel/lib/kautham$ cd
usman@usman:~$ kautham-gui
kautham-gui: error while loading shared libraries: libkautham.so.4.0: cannot open shared object file: No such file or directory

**Comment by usman151mrd** [comment]
I have install  Ubuntu 18.04

**Comment by lepalom** [comment]
try:
cd ~/installation/kautham/build/
devel/lib/kautham/kautham-gui

**Comment by usman151mrd** [comment]
```shell

usman@usman:~$ cd ~/installation/kautham/build/
usman@usman:~/installation/kautham/build$ devel/lib/kautham/kautham-gui
Segmentation fault (core dumped)
usman@usman:~/installation/kautham/build$

**Comment by lepalom** [comment]
you have a problem with your path. Try the packages

**Comment by usman151mrd** [comment]
Not solve this issue and still exist.

**Comment by lepalom** [comment]
with the packages just write kautham-gui

**Comment by usman151mrd** [comment]
i already have try with kautham-gui 
but that error appears
error while loading shared libraries: libkautham.so.4.0: cannot open shared object file: No such file or directory

**Comment by lepalom** [comment]
apt-get install kautham-tools

and after in another terminal kautham-gui

**Comment by usman151mrd** [comment]
```shell 
usman@usman:~/installation/kautham/build$ sudo apt install kautham-tools
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package kautham-tools

**Comment by lepalom** [comment]
sudo add-apt-repository ppa:deb-rob/ros-bionic
sudo apt-get update
sudo apt install kautham-tools kautham-ros-osrf

**Comment by usman151mrd** [comment]
Sir Segmentation problem still exist 

```shell
usman@usman:~$ kautham-gui
Segmentation fault (core dumped)
usman@usman:~$

**Comment by lepalom** [comment]
pleasde paste the result of:
ldd /usr/bin/kautham-gui

**Comment by usman151mrd** [comment]
```
	linux-vdso.so.1 (0x00007ffcd2bf8000)
	libkautham.so.4.0 => /usr/local/lib/libkautham.so.4.0 (0x00007f1756456000)
	libSoQt.so.520 => /usr/lib/x86_64-linux-gnu/libSoQt.so.520 (0x00007f17561ac000)
	libCoin.so.80c => /usr/lib/x86_64-linux-gnu/libCoin.so.80c (0x00007f175579f000)
	libQt5Widgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007f1754f58000)
	libboost_system.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.65.1 (0x00007f1754d53000)
	libboost_thread.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.65.1 (0x00007f1754b2e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f175490f000)
	libpugixml.so.1 => /usr/lib/x86_64-linux-gnu/libpugixml.so.1 (0x00007f17546d8000)
	libompl.so.15 => /usr/lib/x86_64-linux-gnu/libompl.so.15 (0x00007f1753f08000)
	libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007f175379f000)
	libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007f1753054000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1752ccb000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f175292d000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1752715000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1752324000)
	libCoin.so.80 => /usr/local/lib/libCoin.so.80 (0x00007f1751796000)
	libassimp.so.4 => /usr/lib/x86_64-linux-gnu/libassimp.so.4 (0x00007f1750dcb000)
	libfcl.so.0.5 => /usr/lib/x86_64-linux-gnu/libfcl.so.0.5 (0x00007f17502e3000)
	libarmadillo.so.8 => /usr/lib/libarmadillo.so.8 (0x00007f17500da000)
	libompl.so.12 => /usr/lib/x86_64-linux-gnu/libompl.so.12 (0x00007f174f980000)
	libode.so.6 => /usr/lib/x86_64-linux-gnu/libode.so.6 (0x00007f174f662000)
	libdrawstuff.so => /usr/local/lib/libdrawstuff.so (0x00007f174f3e7000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007f174f15b000)
	libGLU.so.1 => /usr/lib/x86_64-linux-gnu/libGLU.so.1 (0x00007f174eeec000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f17575c6000)
	libQt5OpenGL.so.5 => /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5 (0x00007f174ec95000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f174e95d000)
	libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007f174e74d000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f174e51b000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f174e313000)
	libboost_serialization.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_serialization.so.1.65.1 (0x00007f174e0d5000)
	libboost_filesystem.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.65.1 (0x00007f174debb000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f174dc89000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f174d9eb000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f174d7ce000)
	libicui18n.so.60 => /usr/lib/x86_64-linux-gnu/libicui18n.so.60 (0x00007f174d32d000)
	libicuuc.so.60 => /usr/lib/x86_64-linux-gnu/libicuuc.so.60 (0x00007f174cf76000)
	libdouble-conversion.so.1 => /usr/lib/x86_64-linux-gnu/libdouble-conversion.so.1 (0x00007f174cd65000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f174cb61000)
	libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f174c84a000)
	libminizip.so.1 => /usr/lib/x86_64-linux-gnu/libminizip.so.1 (0x00007f174c63f000)
	libccd.so.2 => /usr/lib/x86_64-linux-gnu/libccd.so.2 (0x00007f174c434000)
	libblas.so.3 => /usr/lib/x86_64-linux-gnu/libblas.so.3 (0x00007f174be72000)
	liblapack.so.3 => /usr/lib/x86_64-linux-gnu/liblapack.so.3 (0x00007f174b5b3000)
	libarpack.so.2 => /usr/lib/x86_64-linux-gnu/libarpack.so.2 (0x00007f174b369000)
	libsuperlu.so.5 => /usr/lib/x86_64-linux-gnu/libsuperlu.so.5 (0x00007f174b0f9000)
	libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007f174aec8000)
	libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007f174ac12000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f174a9ea000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f174a7d8000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f174a524000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f174a2f7000)
	libicudata.so.60 => /usr/lib/x86_64-linux-gnu/libicudata.so.60 (0x00007f174874e000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f17484dc000)
	libgfortran.so.4 => /usr/lib/x86_64-linux-gnu/libgfortran.so.4 (0x00007f17480fd000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f1747ef9000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f1747cf3000)
	libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f1747ab3000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f174789e000)

**Comment by lepalom** [comment]
here I see several things: 
1) libCoin.so.80 => /usr/local/lib/libCoin.so.80 (0x00007f1751796000)

please delete your local version of Coin

2) libompl.so.12 => /usr/lib/x86_64-linux-gnu/libompl.so.12

could you install libompl-dev from the lauchpad?

**Comment by usman151mrd** [comment]
can i remove cion using rm command ?
and again install using sudo apt install libcoin80-dev

**Comment by lepalom** [comment]
yes, the local version just:

sudo rm /usr/local/lib/libCoin*

**Comment by usman151mrd** [comment]
i remove local coin library and install libompl-dev from launchpad but Segmentation fault still exist
and create lot of problem after remove local cion library

**Comment by usman151mrd** [comment]
```shell
-- Adding PQP directory
CMake Error at /usr/local/lib/cmake/Coin-4.0.0/coin-export.cmake:74 (message):
  The imported target "Coin::Coin" references the file

     "/usr/local/lib/libCoin.so.4.0.0"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/local/lib/cmake/Coin-4.0.0/coin-export.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/local/lib/cmake/Coin-4.0.0/coin-config.cmake:149 (include)
  src/CMakeLists.txt:26 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/usman/installation/kautham/build/CMakeFiles/CMakeOutput.log".
See also "/home/usman/installation/kautham/build/CMakeFiles/CMakeError.log".

**Comment by lepalom** [comment]
the problem is that you have a mess of local version and system versions. And sorry, I forgot to say to delete:

libkautham.so.4.0 => /usr/local/lib/libkautham.so.4.0 (0x00007f1756456000)

delete /usr/local/lib/cmake/Coin-4.0.0/

and install libcoin-dev

**Comment by usman151mrd** [comment]
In file included from /home/usman/installation/kautham/src/planner/omplOpenDE/PhysicsBasedPlanners/KauthamOpenDEPlanner.cpp:28:0:
/home/usman/installation/kautham/include/kautham/planner/omplOpenDE/PhysicsBasedPlanners/KauthamOpenDEPlanner.h:42:10: fatal error: ompl/extensions/opende/OpenDESimpleSetup.h: No such file or directory
 #include <ompl/extensions/opende/OpenDESimpleSetup.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
src/CMakeFiles/libkautham.dir/build.make:734: recipe for target 'src/CMakeFiles/libkautham.dir/planner/omplOpenDE/PhysicsBasedPlanners/KauthamOpenDEPlanner.cpp.o' failed
make[2]: *** [src/CMakeFiles/libkautham.dir/planner/omplOpenDE/PhysicsBasedPlanners/KauthamOpenDEPlanner.cpp.o] Error 1
CMakeFiles/Makefile2:3037: recipe for target 'src/CMakeFiles/libkautham.dir/all' failed
make[1]: *** [src/CMakeFiles/libkautham.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by usman151mrd** [comment]
after run sudo apt install libimpl-dev
that issue arise and i am tring to solve it.
i create a issue at ompl repository
they replied
```
This appears to be a problem in Kautham, not OMPL. The development version has renamed the opende directory to ode. The binary versions of ompl may been compiled without support for the ODE extension.

```

**Comment by usman151mrd** [comment]
In another system I have install coin library but kautham not able to read that library. and generate issues again and again that coin library missing. even i restart the system.

**Comment by lepalom** [comment]
which version of libompl do you have?

you need ompl built with ode extensions. The package provided in launchpad has that built in. We are using the version released as stable, not the developing version of ompl.

**Comment by lepalom** [comment]
> In another system I have install coin library but kautham not able to read that library. and generate issues again and again that coin library missing. even i restart the system.

as always, which versions do you have and installed from where?

And don't have a mix of local built versions and package version.

**Comment by sohailbukhari** [comment]
CMake Error at src/CMakeLists.txt:26 (find_package):
  Could not find a package configuration file provided by "Coin" with any of
  the following names:

    CoinConfig.cmake
    coin-config.cmake

  Add the installation prefix of "Coin" to CMAKE_PREFIX_PATH or set
  "Coin_DIR" to a directory containing one of the above files.  If "Coin"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/sohxil/installation/kautham/build/CMakeFiles/CMakeOutput.log".
See also "/home/sohxil/installation/kautham/build/CMakeFiles/CMakeError.log".

**Comment by lepalom** [comment]
which is your setup? Ubuntu, Debian, etc? which versions?

**Comment by sohailbukhari** [comment]
Ubuntu 18.04

**Comment by lepalom** [comment]
sudo add-apt-repository ppa:deb-rob/ros-bionic
sudo apt-get update
sudo apt install kautham-tools kautham-ros-osrf


then you will have a packages of kautham to use. If you want to build yourself kautham:

sudo apt-get install libcoin-dev libsoqt520-dev libompl-dev libassimp-dev libboost-system-dev libboost-serialization-dev libboost-thread-dev libode-dev libfcl-dev libarmadillo-dev libpugixml-dev freeglut3-dev build-essential

**Comment by usman151mrd** [comment]
@lepalom Thanks you so much Sir for your precious help. I have learned alot from you. And again thanks you so much for giving your precious time. I have been  running kautham successfully.
